{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: aerocommand-secrets
  labels:
    {{- include "aerocommand.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}
  MONGO_USER: {{ .Values.secrets.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.MONGO_PASSWORD | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY | quote }}
  MQTT_USERNAME: {{ .Values.secrets.MQTT_USERNAME | quote }}
  MQTT_PASSWORD: {{ .Values.secrets.MQTT_PASSWORD | quote }}
{{- end }}
