apiVersion: v1
kind: ConfigMap
metadata:
  name: aerocommand-config
  namespace: aerocommand
  labels:
    app.kubernetes.io/part-of: aerocommand
data:
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "WARNING"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "aerocommand"
  MONGO_HOST: "mongo-svc"
  MONGO_PORT: "27017"
  MONGO_DB: "aerocommand_telemetry"
  REDIS_HOST: "redis-svc"
  REDIS_PORT: "6379"
  MQTT_BROKER_HOST: "emqx-svc"
  MQTT_BROKER_PORT: "1883"
  MQTT_BROKER_WS_PORT: "8083"
  CORS_ORIGINS: '["https://app.aerocommand.io"]'

