# NOTE: In production, use External Secrets Operator or Sealed Secrets.
# These values are BASE64-encoded placeholders only.
apiVersion: v1
kind: Secret
metadata:
  name: aerocommand-secrets
  namespace: aerocommand
  labels:
    app.kubernetes.io/part-of: aerocommand
type: Opaque
data:
  # echo -n 'value' | base64
  POSTGRES_USER: YWVyb2NvbW1hbmQ=                    # aerocommand
  POSTGRES_PASSWORD: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04= # CHANGE_ME_IN_PRODUCTION
  MONGO_USER: YWVyb2NvbW1hbmQ=
  MONGO_PASSWORD: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  REDIS_PASSWORD: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  JWT_SECRET_KEY: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  MQTT_USERNAME: YWVyb2NvbW1hbmQ=
  MQTT_PASSWORD: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=

